# Generated by Django 5.2 on 2025-04-17 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='Server',
            new_name='server',
        ),
        migrations.RenameField(
            model_name='server',
            old_name='ip_address',
            new_name='ip_add',
        ),
        migrations.RemoveField(
            model_name='server',
            name='app_usage',
        ),
        migrations.RemoveField(
            model_name='server',
            name='cpu_usage',
        ),
        migrations.RemoveField(
            model_name='server',
            name='disk_usage',
        ),
        migrations.RemoveField(
            model_name='server',
            name='ram_usage',
        ),
        migrations.AlterField(
            model_name='server',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_usage', models.FloatField()),
                ('ram_usage', models.FloatField()),
                ('disk_usage', models.FloatField()),
                ('app_usage', models.FloatField()),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.server')),
            ],
        ),
    ]
